name: 'Log Scanner'
description: 'Scan logs from previous actions for specific strings'
author: 'niklas-weber'
inputs:
  error:
    required: true
    description: 'Regex for error string'
    default: '^ERROR.*'
  gh-token:
    required: true
    description: 'Github repo token'
  run-id:
    required: true
    description: 'Github run ID'
  job-name:
    required: true
    description: 'Current Job name'
  repo-owner:
    required: true
    description: 'Repo owner'
  repo-name:
    required: true
    description: 'Repo name'
  
runs:
  using: 'node16'
  main: 'dist/index.js'
