name: 'Log Scanner'
description: 'Scan logs from previous actions for specific strings'
author: 'niklas-weber'
inputs:
  error: # change this
    required: true
    description: 'Regex for error string'
    default: '^ERROR.*'
runs:
  using: 'node18'
  main: 'dist/index.js'
