name: 'Log Scanner'
description: 'Scan logs from previous actions for specific strings'
author: 'niklas-weber'
inputs:
  error:
    required: true
    description: 'Regex for error string'
    default: '^ERROR.*'
  gh-token:
    required: true
    description: 'Github repo token'
runs:
  using: 'node16'
  main: 'dist/index.js'
