name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - develop
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  error-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ERROR
  test: # make sure the action works on a clean machine without building
    needs: 'error-job'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          error: '^ERROR.*'
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.run_id }}
          job-name: 'error-job'
          repo-name: scan-log
          repo-owner: niklas-weber
      - name: Failure check
        if: ${{ failure() }}
        run: exit 0
